# Generated by Flutter – custom rules for release builds.

# --- General Flutter / Platform Channel Rules ---
# Keep Flutter platform channel interface and Pigeon-generated code
-keep class io.flutter.plugin.common.** { *; }
-keep class io.flutter.plugins.** { *; }
-keep class * extends io.flutter.plugin.common.MethodChannel { *; }
-keep @interface io.flutter.plugin.common.MethodCodec
-keep class * implements io.flutter.plugin.common.MethodCodec { *; }

# Keep Pigeon-generated classes (CRITICAL for Google Sign-in and others)
-keep class dev.flutter.pigeon.** { *; }

# Keep path_provider specifically
-keep class io.flutter.plugins.pathprovider.** { *; }
-keep class dev.flutter.pigeon.path_provider_android.** { *; }

# Keep GeneratedPluginRegistrant to ensure plugins are registered
-keep class io.flutter.plugins.GeneratedPluginRegistrant { *; }

# --- Google Sign-In & Firebase ---
-keep class com.google.android.gms.** { *; }
-keep class com.google.android.gms.auth.api.signin.** { *; }
-keep class com.google.android.gms.common.api.** { *; }
-keep class com.google.firebase.** { *; }
-dontwarn com.google.android.gms.**
-dontwarn com.google.firebase.**

# --- Video Player & Chewie ---
-keep class io.flutter.plugins.videoplayer.** { *; }
-keep class androidx.media3.** { *; }
-dontwarn androidx.media3.**

# --- Google Mobile Ads SDK ---
-keep class com.google.android.gms.ads.** { *; }
-keep class com.google.ads.** { *; }
-keep class io.flutter.plugins.googlemobileads.** { *; }

# --- FFmpeg & Native Libraries ---
-keep class com.arthenica.ffmpegkit.** { *; }
-keep class com.google.mlkit.** { *; }

# --- Miscellaneous / Clean Up ---
# Suppress missing javax.xml.stream classes
-dontwarn javax.xml.stream.**

# Suppress warnings for OkHttp (used by AdMob)
-dontwarn com.squareup.okhttp.**
-dontwarn okio.**
